[book]
title = "SML Help"
author = "15-150 staff"
description = "A resource for learning SML"

[build]
build-dir = "docs/"
create-missing = true

[preprocessor.index]

[preprocessor.links]

[output.html]
additional-css = []
mathjax-support = true

[output.html.search]
limit-results = 15

